Improved installation error detection.
This version of installpkg will report errors and non-zero exit values on additional errors which would have been ignored in previous versions.

The idea is to provide additional feed back to scripts and systems which rely upon installpkg to insall specified packages.

diff --git a/install_components/installpkg b/install_components/installpkg
--- a/install_components/installpkg
+++ b/install_components/installpkg
@@ -9,7 +9,7 @@
 # Installs multiple pagkages, by simply specifing the items on the command line
 # All items will be installed to the root directory.
 
-# Version 0.1.5
+# Version 0.1.6
 
 function check_admin_rights {
 
@@ -78,7 +78,7 @@ function check_package {
 
     darwin_release_version=`uname -r | awk -F "." '{print $1}'`
     leapoard_relese_version=9
-    
+		
     if [ -d "${item2add}" ] ; then
         return 0
     else
@@ -109,19 +109,25 @@ function check_image {
 function install_package {
 
     check_package
-    
     if [ $? == 0 ] ; then
-    
         #Installing Package
         sudo installer -pkg "${item2add}" -target /
-
-    fi
+		if [ $? != 0 ] ; then
+			((num_installer_errors++))
+			echo "WARNING! : Errors were encountered during installation of package : ${item2add}"
+		else
+			((num_installed_packages_or_images++))
+		fi
+	else
+		((num_installer_errors++))
+	fi
 
 }
 
 
 function mount_package {
 
+	number_of_packages_installed_from_image=0
 	image_already_mounted="NO"
     check_image
     if [ $? == 0 ] ; then
@@ -138,28 +144,51 @@ function mount_package {
 		if [ "${image_mount_point}" == "" ] ; then
 			echo "ERROR! : Unable to mount item."
 			((num_dmg_failed_to_mount++))
+			return -1
 		else
 			# if sucessful recursivly call installpkg to install the package.
 			sudo installpkg -q /Volumes/"${image_mount_point}"/*
+			if [ $? != 0 ] ; then
+				((num_installer_errors++))	
+			else
+				((number_of_packages_installed_from_image++))
+			fi
 		
 			# unmount the package if it was not already mounted and we managed to mount it earlier.
 	        if [ "${image_already_mounted}" == "NO" ] ; then
+				sleep 1
 				hdiutil detach /Volumes/"${image_mount_point}" > /dev/null
 				if [ $? != 0 ] ; then
-					echo "ERROR! : Unable to unmount item."
+					sleep 3
+					hdiutil detach /Volumes/"${image_mount_point}" -force > /dev/null
+					if [ $? != 0 ] ; then
+						echo "WARNING! : Unable to unmount item : /Volumes/${image_mount_point}"
+					else
+						echo "Item unmounted."
+					fi
 				else
 					echo "Item unmounted."
 				fi
 			fi
 		fi
-
     fi
+	
+	if [ $num_dmg_failed_to_mount -gt 0 ] ; then
+		echo "ERROR : No packages were installed from the image"
+		return -1
+	else
+		return 0 
+	fi
 
 }
 
 
 function check_is_pkg {
-        
+     
+	# Alterative approach   
+	# file_suffix=`echo "${item2add##*.}"`
+    # if [ ".${download_suffix}" == ".pkg" ] || [ ".${download_suffix}" == ".mpkg" ] ; then 
+		
     extension1=`basename "${item2add}" | tail -c 5`
     extension2=`basename "${item2add}" | tail -c 6`
     if [ "${extension1}" == ".pkg" ] || [ "${extension2}" == ".mpkg" ] ; then 
@@ -167,6 +196,7 @@ function check_is_pkg {
         return 1
     else
         # This item is not an installer package
+		echo "WARNING! : Item is not a package and has not been installed : ${item2add}"
         return 0
     fi
         
@@ -211,11 +241,12 @@ function download_from_url_to_temporary_directory {
 	cd "${download_directory}"
 	if [ $? != 0 ] ; then 
 		echo "ERROR! : Unable to change directory to the download direcotry."
-		echo "         No attempt will be made to install any further packages which have yet to installed."
+		echo "         No attempt will be made to install any further packages which have yet to be installed."
 	    exit_status=-123
 	    exit_now
 	fi
 	followed_redirects_actual_download_url=`wget --spider "${item2add}" 2>&1 | grep -e "^Location" | awk '{print $2}' | tail -n 1`
+	if [ "${followed_redirects_actual_download_url}" == "" ] ; then followed_redirects_actual_download_url="${item2add}" ; fi
 	downloaded_file_name=`basename "${followed_redirects_actual_download_url}"`
 	wget ${wget_options}--backups=0 "${item2add}" -O "${downloaded_file_name}"
 	if [ $? != 0 ] ; then 
@@ -253,6 +284,8 @@ num_dmg_failed_to_mount=0
 download_directory=/tmp/installpkg_downloads
 item2add=""
 wget_options=""
+num_installer_errors=0
+num_installed_packages_or_images=0
 
 # parse any arguments
 while getopts ":iuq" option
@@ -304,6 +337,11 @@ do
 		 if [ $? == 1 ] ; then
 			echo "Mounting Item : ${item2add}"
 			mount_package
+			if [ $? != 0 ] ; then
+				((num_installer_errors++))
+			else
+				((num_installed_packages_or_images++))	
+			fi
 		 else
 			echo "WARNING! : Item is not a dynamic image file : ${item2add}"
 			echo "           Item has not been mounted or installed"
@@ -311,11 +349,8 @@ do
 	else 
 	    check_is_pkg
 	    if [ $? == 1 ] ; then
-		echo "Installing Item : ${item2add}"
-		install_package
-	    else
-		echo "WARNING! : Item is not a package : ${item2add}"
-		echo "           Item has not been installed"
+			echo "Installing Item : ${item2add}"
+			install_package
 	    fi
 	fi
 
@@ -328,13 +363,21 @@ done
 
 
 if [ $quite_mode_enabled == 0 ] ; then
-	echo ""
-	echo ""
-	echo "----------------------------------------------------------------------------"
-	echo "Summary : "
-	echo ""
-	echo "If any of these packages required reboots, then you should restart your computer."
-	echo "To restart the machine type : sudo shutdown -r now"
+	if [ $num_installed_packages_or_images -gt 0 ] ; then 
+		echo ""
+		echo ""
+		echo "----------------------------------------------------------------------------"
+		echo "Summary : "
+		echo ""
+		echo "If any of these packages required reboots, then you should restart your computer."
+		echo "To restart the machine type : sudo shutdown -r now"
+	else
+		echo "----------------------------------------------------------------------------"
+		echo "Summary : "
+		echo ""
+		echo "    ERROR! : No packages (.pkg or .mpkg) or images (.dmg) were installed."
+		echo ""	
+	fi
 	if [ $num_dmg_failed_to_mount -gt 0 ] ; then
 		echo ""
 		echo "    WARNING : [${num_dmg_failed_to_mount}] items were .dmg files and they were not able to mounted."
@@ -342,12 +385,24 @@ if [ $quite_mode_enabled == 0 ] ; then
 		echo "              these images file (.dmg) files will not have been installed."
 		echo ""
 	fi
-	echo ""
+	if [ $num_installer_errors -gt 0 ] ; then
+		echo ""
+		echo "    WARNING : [${num_installer_errors}] packages or images failed installation."
+		echo ""
+	fi
 fi
 
 # if [ $num_dmg_failed_to_mount -gt 0 ] ; then
-#         exit_status=-130
+#   exit_status=-130
 # fi
+
+if [ $num_installer_errors -gt 0 ] ; then
+	exit_status=-131
+fi
+
+if [ $num_installed_packages_or_images == 0 ] ; then
+	exit_status=-130
+fi
 
 exit_now
 
